kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "1847a369-5a25-4d1b-8cad-5740988d4423",
        "label": "Sample AS3 Template",
        "remark": "HTTP application",
        "stark": {
          "class": "Tenant",
          "blog": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.0.6.100"
              ],
              "virtualPort": 80,
              "pool": "web_pool"
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 8080,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
